;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Pawn.Character",NewTagName="Pawn.Hero")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ability.basicattack",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo01",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo02",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo03",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo04",DevComment="")
+GameplayTagList=(Tag="ability.combo.end",DevComment="")
+GameplayTagList=(Tag="ability.data.damage",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.eskill.damage",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.eskill.spawn",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.qskill.damage",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.qskill.damageratio",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.qskill.spawn",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.rmskill",DevComment="")
+GameplayTagList=(Tag="ability.shinbi.rmskill.dashland",DevComment="")
+GameplayTagList=(Tag="ability.state.casting",DevComment="")
+GameplayTagList=(Tag="ability.state.charging",DevComment="")
+GameplayTagList=(Tag="ability.state.movement.blocked",DevComment="")
+GameplayTagList=(Tag="ability.target.damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.camerashake",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.shinbi.basicattack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.shinbi.eskill",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.shinbi.qskill",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.shinbi.rmskill",DevComment="")
+GameplayTagList=(Tag="GameplayCue.shinbi.eskill.cast",DevComment="")
+GameplayTagList=(Tag="Pawn.Gaurdian",DevComment="Gaurdian Class")
+GameplayTagList=(Tag="Pawn.Hero",DevComment="Character Class")
+GameplayTagList=(Tag="Pawn.Minion",DevComment="Minion Class")

