;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Pawn.Character",NewTagName="Pawn.Hero")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ability.basicattack",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo01",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo02",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo03",DevComment="")
+GameplayTagList=(Tag="ability.combo.combo04",DevComment="")
+GameplayTagList=(Tag="ability.combo.end",DevComment="")
+GameplayTagList=(Tag="ability.data.damage",DevComment="")
+GameplayTagList=(Tag="ability.target.damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.shinbi.basicattack",DevComment="")
+GameplayTagList=(Tag="Pawn.Gaurdian",DevComment="Gaurdian Class")
+GameplayTagList=(Tag="Pawn.Hero",DevComment="Character Class")
+GameplayTagList=(Tag="Pawn.Minion",DevComment="Minion Class")

